# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuckUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_coord', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon_coord', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('money', models.IntegerField(default=100)),
                ('drugs', models.FloatField(default=0)),
                ('last_drug_transaction', models.DateTimeField(blank=True, null=True)),
                ('session_auth', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuck_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
