# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuckuser',
            name='session_auth',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cuckuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuck_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
