# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160917_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuckuser',
            old_name='x_coord',
            new_name='lat_coord',
        ),
        migrations.RenameField(
            model_name='cuckuser',
            old_name='y_coord',
            new_name='lon_coord',
        ),
    ]
