# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160917_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuckuser',
            name='money',
            field=models.IntegerField(default=100),
        ),
    ]
