# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160918_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mugging',
            name='narc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narc_set', to='api.CuckUser'),
        ),
    ]
