# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160918_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('msg', models.CharField(choices=[('mug', 'You are being mugged!')], max_length=8)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.CuckUser')),
            ],
        ),
    ]
