# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_notification_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.CuckUser'),
        ),
    ]
